CREATE DATABASE ORG123;
SHOW DATABASES;
USE ORG123;

CREATE TABLE Worker (
	WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME CHAR(25),
	LAST_NAME CHAR(25),
	SALARY INT(15),
	JOINING_DATE DATETIME,
	DEPARTMENT CHAR(25)
);

INSERT INTO Worker 
	(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(001, 'Monika', 'Arora', 100000, '14-02-20 09.00.00', 'HR'),
		(002, 'Niharika', 'Verma', 80000, '14-06-11 09.00.00', 'Admin'),
		(003, 'Vishal', 'Singhal', 300000, '14-02-20 09.00.00', 'HR'),
		(004, 'Amitabh', 'Singh', 500000, '14-02-20 09.00.00', 'Admin'),
		(005, 'Vivek', 'Bhati', 500000, '14-06-11 09.00.00', 'Admin'),
		(006, 'Vipul', 'Diwan', 200000, '14-06-11 09.00.00', 'Account'),
		(007, 'Satish', 'Kumar', 75000, '14-01-20 09.00.00', 'Account'),
		(008, 'Geetika', 'Chauhan', 90000, '14-04-11 09.00.00','Admin');
        
        
        SELECT FIRST_NAME, SUM(SALARY) FROM Worker GROUP BY FIRST_NAME
        ORDER BY FIRST_NAME ASC;
        
        SELECT JOINING_DATE, AVG(SALARY) FROM Worker GROUP BY JOINING_DATE
        ORDER BY JOINING_DATE DESC;
        
        SELECT SALARY, MAX(SALARY) FROM Worker GROUP BY SALARY
        ORDER BY SALARY ASC;
        
        SELECT DEPARTMENT, MIN(SALARY) FROM Worker GROUP BY DEPARTMENT
        ORDER BY DEPARTMENT DESC;
        
        
        SELECT COUNT(*) FROM WORKER WHERE DEPARTMENT NOT IN ('HR', 'Admin');
        
        SELECT DEPARTMENT, MAX(SALARY) FROM Worker GROUP BY DEPARTMENT
        ORDER BY DEPARTMENT ASC;
        
        SELECT UPPER(FIRST_NAME) FROM Worker;
        SELECT LOWER(LAST_NAME) FROM Worker;
        SELECT SUBSTRING(FIRST_NAME, 1, 3) AS NICKNAME FROM Worker;
        SELECT FIRST_NAME, INSTR(FIRST_NAME, 'a') AS INDEX_OF_A FROM Worker;
        SELECT REPLACE(FIRST_NAME, 'm', 'A') FROM WORKER;
        SELECT CONCAT(FIRST_NAME, ' ' , LAST_NAME) FROM WORKER;
        SELECT * FROM WORKER ORDER BY SALARY DESC LIMIT 2 OFFSET 5;
        SELECT * FROM WORKER ORDER BY SALARY DESC;